name: nodejs-build
on: 
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - .github/workflows/*.yaml
  issues:
    types:
      - opened
      - closed
  workflow_dispatch: 
jobs:
  gitcheckout:
    runs-on: self-hosted
    steps:
      - name: git-checkout
        uses: actions/checkout@v7
  compile_and_buid:
    runs-on: self-hosted
    needs: gitcheckout
    steps:
      - name: test
        working-directory: ./src
        run:  npm test
      - name: compilation
        working-directory: ./src
        run: npm ci install
      - name: build
        run: npm start
          
